require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const app = express();
app.use(helmet());
app.use(cors({ origin: '*', credentials: true }));
app.use(rateLimit({ windowMs: 15*60*1000, max: 100 }));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use('/api/auth/google', require('./src/routes/googleAuth'));
app.use('/api/auth', require('./src/routes/auth'));
app.use('/api/tutors', require('./src/routes/tutors'));
app.use('/api/bookings', require('./src/routes/bookings'));
app.use('/api/payments', require('./src/routes/payments'));
app.use('/api/packages', require('./src/routes/packages'));
app.use('/api/earnings', require('./src/routes/earnings'));
app.use('/api/messages', require('./src/routes/messages'));
const passport = require('passport');
app.use(passport.initialize());
app.use('/api/auth/google', require('./src/routes/googleAuth'));
app.use('/api/subjects', require('./src/routes/subjects'));
app.use('/api/support', require('./src/routes/support'));
app.use('/api/admin', require('./src/routes/admin'));
app.get('/health', (req, res) => res.status(200).json({ status: 'ok' }));
app.use((err, req, res, next) => res.status(500).json({ error: 'Server error' }));
const PORT = process.env.PORT || process.env.PORT || 3001;
app.listen(PORT, '0.0.0.0', () => console.log('BILIMLY RUNNING on port ' + PORT));
